steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']
    dir: 'frontend'

  # Run tests
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'test']
    dir: 'frontend'

  # Build the application
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    dir: 'frontend'

  # Optional: Deploy to Cloud Storage or App Engine
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['app', 'deploy']
  #   dir: 'frontend'

timeout: '1800s' # Set build timeout to 30 minutes
